package com.rafaelfelipeac.hermes.core.useraction.metadata

object UserActionMetadataKeys {
    const val WEEK_START_DATE = "week_start_date"
    const val OLD_WEEK_START_DATE = "old_week_start_date"
    const val NEW_WEEK_START_DATE = "new_week_start_date"
    const val DAY_OF_WEEK = "day_of_week"
    const val OLD_DAY_OF_WEEK = "old_day_of_week"
    const val NEW_DAY_OF_WEEK = "new_day_of_week"
    const val OLD_TIME_SLOT = "old_time_slot"
    const val NEW_TIME_SLOT = "new_time_slot"
    const val OLD_ORDER = "old_order"
    const val NEW_ORDER = "new_order"
    const val OLD_TYPE = "old_type"
    const val NEW_TYPE = "new_type"
    const val OLD_DESCRIPTION = "old_description"
    const val NEW_DESCRIPTION = "new_description"
    const val OLD_VALUE = "old_value"
    const val NEW_VALUE = "new_value"
    const val OLD_CATEGORY_NAME = "old_category_name"
    const val NEW_CATEGORY_NAME = "new_category_name"
    const val WAS_COMPLETED = "was_completed"
    const val IS_COMPLETED = "is_completed"
    const val CATEGORY_NAME = "category_name"
}
