package com.rafaelfelipeac.hermes.core.useraction

enum class UserActionType {
    CREATE_WORKOUT,
    UPDATE_WORKOUT,
    DELETE_WORKOUT,
    COMPLETE_WORKOUT,
    INCOMPLETE_WORKOUT,
    REORDER_WORKOUT,
    MOVE_WORKOUT_BETWEEN_DAYS,
    CREATE_REST_DAY,
    UPDATE_REST_DAY,
    DELETE_REST_DAY,
    CONVERT_WORKOUT_TO_REST_DAY,
    CONVERT_REST_DAY_TO_WORKOUT,
    OPEN_WEEK,
    CHANGE_THEME,
    CHANGE_LANGUAGE,
}
