package com.rafaelfelipeac.hermes.features.trophies.domain.model

enum class TrophyMetric {
    COMPLETED_WEEKS,
    WORKOUT_COMPLETIONS,
    CONSECUTIVE_COMPLETED_WEEKS,
    COMEBACK_WEEKS,
    PLANNING_ADJUSTMENTS,
    COPIED_WEEKS,
    COPIED_AND_COMPLETED_WEEKS,
    CATEGORY_ACTIONS,
    BACKUP_SUCCESSES,
    WORKOUT_CREATIONS,
    PROTECTED_TIME_BLOCKS,
    CATEGORY_COMPLETIONS,
    CATEGORY_PRESENCE_WEEKS,
    CATEGORY_PLANNING_ACTIONS,
}
